/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_leonardomontoya;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Inspiron
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdi_universo = new javax.swing.JDialog();
        jtf_codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_universo = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jd_mundo = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jtf_ntorgua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        js_pesomundo = new javax.swing.JSpinner();
        btn_gmundo = new javax.swing.JButton();
        jd_criaturas = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_raza = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_objetos = new javax.swing.JTextArea();
        js_vivos = new javax.swing.JSpinner();
        js_anioscriatura = new javax.swing.JSpinner();
        jtf_region = new javax.swing.JTextField();
        btn_nuevacriatura = new javax.swing.JButton();
        js_energia = new javax.swing.JSpinner();
        js_pesocaricatura = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jpm_mundos = new javax.swing.JPopupMenu();
        jm_agregar = new javax.swing.JMenuItem();
        jm_eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenu();
        jmu_nombremundo = new javax.swing.JMenuItem();
        jmu_pesomundo = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        Cuniverso = new javax.swing.JButton();
        btn_mundo = new javax.swing.JButton();
        btn_criatura = new javax.swing.JButton();
        btn_mundotree = new javax.swing.JButton();
        btn_criaturatotree = new javax.swing.JButton();
        btn_pesouniverso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_universo = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_mundos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlist_criaturas = new javax.swing.JList<>();

        jLabel1.setText("Codigo");

        jLabel2.setText("Edad");

        jLabel3.setText("Crear Universo");

        btn_universo.setText("Crear Universo");
        btn_universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_universoMouseClicked(evt);
            }
        });

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(50, 0, null, 1));

        javax.swing.GroupLayout jdi_universoLayout = new javax.swing.GroupLayout(jdi_universo.getContentPane());
        jdi_universo.getContentPane().setLayout(jdi_universoLayout);
        jdi_universoLayout.setHorizontalGroup(
            jdi_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdi_universoLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jdi_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdi_universoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdi_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jdi_universoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jdi_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_universo)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)))
                .addGap(70, 70, 70))
        );
        jdi_universoLayout.setVerticalGroup(
            jdi_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdi_universoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jdi_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdi_universoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btn_universo)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLabel4.setText("Crear Mundo Disco");

        jLabel5.setText("Nombre de Tortuga");

        jLabel6.setText("Peso");

        js_pesomundo.setModel(new javax.swing.SpinnerNumberModel(50, 0, null, 1));

        btn_gmundo.setText("Crear Mundo");
        btn_gmundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gmundoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mundoLayout = new javax.swing.GroupLayout(jd_mundo.getContentPane());
        jd_mundo.getContentPane().setLayout(jd_mundoLayout);
        jd_mundoLayout.setHorizontalGroup(
            jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundoLayout.createSequentialGroup()
                .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mundoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_ntorgua, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_pesomundo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_mundoLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_gmundo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jd_mundoLayout.setVerticalGroup(
            jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_ntorgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jd_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(js_pesomundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btn_gmundo)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLabel7.setText("Criatura");

        jLabel8.setText("Nombre de Raza");

        jLabel9.setText("Numero de Energia");

        jLabel10.setText("Numero max de años");

        jLabel11.setText("Nombre de la Region");

        jLabel12.setText("Cantidad Vivos");

        jLabel13.setText("Lista de objetos");

        ta_objetos.setColumns(20);
        ta_objetos.setRows(5);
        jScrollPane4.setViewportView(ta_objetos);

        js_vivos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        js_anioscriatura.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btn_nuevacriatura.setText("Crear Criatura");
        btn_nuevacriatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevacriaturaMouseClicked(evt);
            }
        });

        js_energia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        js_pesocaricatura.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel14.setText("Peso");

        javax.swing.GroupLayout jd_criaturasLayout = new javax.swing.GroupLayout(jd_criaturas.getContentPane());
        jd_criaturas.getContentPane().setLayout(jd_criaturasLayout);
        jd_criaturasLayout.setHorizontalGroup(
            jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_criaturasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jd_criaturasLayout.createSequentialGroup()
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jd_criaturasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_criaturasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_criaturasLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_vivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_anioscriatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtf_region, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btn_nuevacriatura, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_pesocaricatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jd_criaturasLayout.setVerticalGroup(
            jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_criaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_criaturasLayout.createSequentialGroup()
                        .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(js_energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(js_anioscriatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(js_vivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_criaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(js_pesocaricatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btn_nuevacriatura)
                .addGap(22, 22, 22))
        );

        jm_agregar.setText("Agregar");
        jm_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_agregarActionPerformed(evt);
            }
        });
        jpm_mundos.add(jm_agregar);

        jm_eliminar.setText("Eliminar");
        jm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarActionPerformed(evt);
            }
        });
        jpm_mundos.add(jm_eliminar);

        Modificar.setText("modificar");

        jmu_nombremundo.setText("Nombre");
        jmu_nombremundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmu_nombremundoActionPerformed(evt);
            }
        });
        Modificar.add(jmu_nombremundo);

        jmu_pesomundo.setText("Peso");
        jmu_pesomundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmu_pesomundoActionPerformed(evt);
            }
        });
        Modificar.add(jmu_pesomundo);

        jpm_mundos.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        Cuniverso.setText("Crear Universo");
        Cuniverso.setFocusable(false);
        Cuniverso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cuniverso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cuniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CuniversoMouseClicked(evt);
            }
        });
        jToolBar1.add(Cuniverso);

        btn_mundo.setText("Crear Mundo");
        btn_mundo.setEnabled(false);
        btn_mundo.setFocusable(false);
        btn_mundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mundo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mundoMouseClicked(evt);
            }
        });
        btn_mundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mundoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mundo);

        btn_criatura.setText("Añadir Criatura Lista");
        btn_criatura.setEnabled(false);
        btn_criatura.setFocusable(false);
        btn_criatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_criatura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_criatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_criaturaMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_criatura);

        btn_mundotree.setText("Añadir Mundo a Universo");
        btn_mundotree.setEnabled(false);
        btn_mundotree.setFocusable(false);
        btn_mundotree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mundotree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mundotree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mundotreeMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_mundotree);

        btn_criaturatotree.setText("Agregar Criatura al arbol");
        btn_criaturatotree.setEnabled(false);
        btn_criaturatotree.setFocusable(false);
        btn_criaturatotree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_criaturatotree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_criaturatotree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_criaturatotreeMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_criaturatotree);

        btn_pesouniverso.setText("Informacion del Universo");
        btn_pesouniverso.setEnabled(false);
        btn_pesouniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pesouniversoMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_pesouniverso);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo");
        jt_universo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_universo);

        jlist_mundos.setModel(new DefaultListModel());
        jlist_mundos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlist_mundosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jlist_mundos);

        jlist_criaturas.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jlist_criaturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_universoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_universoMouseClicked
        // TODO add your handling code here:
        u.setCodigo(jtf_codigo.getText());
        u.setEdad((Integer) jSpinner2.getValue());
        u.setPeso(0);
        btn_pesouniverso.setEnabled(true);
        btn_mundo.setEnabled(true);
        btn_criatura.setEnabled(true);
        btn_mundotree.setEnabled(true);
        btn_criaturatotree.setEnabled(true);
        Cuniverso.setEnabled(false);
        jtf_codigo.setText("");
        jSpinner2.setValue(50);
        jdi_universo.dispose();

    }//GEN-LAST:event_btn_universoMouseClicked

    private void CuniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuniversoMouseClicked
        // TODO add your handling code here:
        if (Cuniverso.isEnabled() == true) {
            jdi_universo.setModal(true);
            jdi_universo.pack();
            jdi_universo.setLocationRelativeTo(this);
            jdi_universo.setVisible(true);
        }
    }//GEN-LAST:event_CuniversoMouseClicked

    private void btn_gmundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gmundoMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jlist_mundos.getModel();
        modelo.addElement(new MundoDisco(jtf_ntorgua.getText(), (Integer) js_pesomundo.getValue()));
        jlist_mundos.setModel(modelo);
        jtf_ntorgua.setText("");
        js_pesomundo.setValue(50);
        jd_mundo.setVisible(false);
    }//GEN-LAST:event_btn_gmundoMouseClicked

    private void btn_mundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mundoMouseClicked
        // TODO add your handling code here:

        if (btn_mundo.isEnabled() == true) {
            jd_mundo.setModal(true);
            jd_mundo.pack();
            jd_mundo.setLocationRelativeTo(this);
            jd_mundo.setVisible(true);
        }

    }//GEN-LAST:event_btn_mundoMouseClicked

    private void btn_criaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_criaturaMouseClicked
        // TODO add your handling code here:
        if (btn_criatura.isEnabled()) {
            jd_mundo.setModal(true);
            jd_criaturas.pack();
            jd_criaturas.setLocationRelativeTo(this);
            jd_criaturas.setVisible(true);
        }
    }//GEN-LAST:event_btn_criaturaMouseClicked

    private void btn_mundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mundoActionPerformed

    private void btn_nuevacriaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevacriaturaMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jlist_criaturas.getModel();
        String[] objetos = ta_objetos.getText().split("\n");
        modelo.addElement(new criatura(jtf_raza.getText(), (Integer) js_energia.getValue(), (Integer) js_anioscriatura.getValue(), jtf_region.getText(), (Integer) js_vivos.getValue(), (Integer) js_pesocaricatura.getValue()));
        jlist_criaturas.setModel(modelo);
        jtf_raza.setText("");
        jtf_region.setText("");
        jd_criaturas.setVisible(false);
    }//GEN-LAST:event_btn_nuevacriaturaMouseClicked

    private void btn_mundotreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mundotreeMouseClicked
        // TODO add your handling code here:
        if (jlist_mundos.getSelectedIndex() >= 0) {
            DefaultTreeModel m = (DefaultTreeModel) jt_universo.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultListModel modeloLISTA = (DefaultListModel) jlist_mundos.getModel();
            DefaultMutableTreeNode mundo = new DefaultMutableTreeNode((MundoDisco) modeloLISTA.get(jlist_mundos.getSelectedIndex()));
            raiz.add(mundo);
            u.setPeso(u.getPeso() + ((MundoDisco) modeloLISTA.get(jlist_mundos.getSelectedIndex())).getPeso());
            modeloLISTA.remove(jlist_mundos.getSelectedIndex());
            jlist_mundos.setModel(modeloLISTA);
            m.reload();

        }
    }//GEN-LAST:event_btn_mundotreeMouseClicked

    private void btn_criaturatotreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_criaturatotreeMouseClicked
        // TODO add your handling code here:
        if (btn_mundotree.isEnabled()) {
            if (jt_universo.getSelectionCount() > 0) {
                DefaultTreeModel m = (DefaultTreeModel) jt_universo.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultMutableTreeNode n = (DefaultMutableTreeNode) jt_universo.getSelectionPath().getLastPathComponent();
                if (jlist_criaturas.getSelectedIndex() >= 0 && n.getUserObject() instanceof MundoDisco) {
                    DefaultListModel modeloLISTA = (DefaultListModel) jlist_criaturas.getModel();
                    DefaultMutableTreeNode c = new DefaultMutableTreeNode((criatura) modeloLISTA.get(jlist_criaturas.getSelectedIndex()));
                    u.setPeso(u.getPeso() + (((criatura) modeloLISTA.get(jlist_criaturas.getSelectedIndex())).getPeso()) * ((criatura) modeloLISTA.get(jlist_criaturas.getSelectedIndex())).getNumespecies());
                    n.add(c);
                    m.reload();
                    modeloLISTA.remove(jlist_criaturas.getSelectedIndex());
                    jlist_criaturas.setModel(modeloLISTA);
                }
            }
        }
    }//GEN-LAST:event_btn_criaturatotreeMouseClicked

    private void jlist_mundosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlist_mundosMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            jpm_mundos.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jlist_mundosMouseClicked

    private void jm_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_agregarActionPerformed
        // TODO add your handling code here:
        if (btn_mundo.isEnabled() == true) {
            jd_mundo.setModal(true);
            jd_mundo.pack();
            jd_mundo.setLocationRelativeTo(this);
            jd_mundo.setVisible(true);
        }
    }//GEN-LAST:event_jm_agregarActionPerformed

    private void jm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarActionPerformed
        // TODO add your handling code here:
        if (jlist_mundos.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jlist_mundos.getModel();
            modelo.remove(jlist_mundos.getSelectedIndex());
            jlist_mundos.setModel(modelo);
        }
    }//GEN-LAST:event_jm_eliminarActionPerformed

    private void jmu_nombremundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmu_nombremundoActionPerformed
        // TODO add your handling code here:
        if (jlist_mundos.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jlist_mundos.getModel();
            ((MundoDisco) modelo.get(jlist_mundos.getSelectedIndex())).setNombre(JOptionPane.showInputDialog(this, "Ingrese nuevo nombre"));
            jlist_mundos.setModel(modelo);
        }
    }//GEN-LAST:event_jmu_nombremundoActionPerformed

    private void jmu_pesomundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmu_pesomundoActionPerformed
        // TODO add your handling code here:
        if (jlist_mundos.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jlist_mundos.getModel();
            ((MundoDisco) modelo.get(jlist_mundos.getSelectedIndex())).setPeso(Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese nuevo nombre")));
            jlist_mundos.setModel(modelo);
        }
    }//GEN-LAST:event_jmu_pesomundoActionPerformed

    private void btn_pesouniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pesouniversoMouseClicked
        // TODO add your handling code here:
        if (btn_pesouniverso.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Codigo:" + u.getCodigo() + "\n Edad: " + u.getEdad() + "\n Peso: " + u.getPeso());
        }
    }//GEN-LAST:event_btn_pesouniversoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cuniverso;
    private javax.swing.JMenu Modificar;
    private javax.swing.JButton btn_criatura;
    private javax.swing.JButton btn_criaturatotree;
    private javax.swing.JButton btn_gmundo;
    private javax.swing.JButton btn_mundo;
    private javax.swing.JButton btn_mundotree;
    private javax.swing.JButton btn_nuevacriatura;
    private javax.swing.JButton btn_pesouniverso;
    private javax.swing.JButton btn_universo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_criaturas;
    private javax.swing.JDialog jd_mundo;
    private javax.swing.JDialog jdi_universo;
    private javax.swing.JList<String> jlist_criaturas;
    private javax.swing.JList<String> jlist_mundos;
    private javax.swing.JMenuItem jm_agregar;
    private javax.swing.JMenuItem jm_eliminar;
    private javax.swing.JMenuItem jmu_nombremundo;
    private javax.swing.JMenuItem jmu_pesomundo;
    private javax.swing.JPopupMenu jpm_mundos;
    private javax.swing.JSpinner js_anioscriatura;
    private javax.swing.JSpinner js_energia;
    private javax.swing.JSpinner js_pesocaricatura;
    private javax.swing.JSpinner js_pesomundo;
    private javax.swing.JSpinner js_vivos;
    private javax.swing.JTree jt_universo;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_ntorgua;
    private javax.swing.JTextField jtf_raza;
    private javax.swing.JTextField jtf_region;
    private javax.swing.JTextArea ta_objetos;
    // End of variables declaration//GEN-END:variables
Universo u = new Universo();
}
